name: Generate Snake Animation 🐍

on:
  schedule:
    - cron: "0 0 * * *" # roda todos os dias à meia-noite UTC
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: jaelsonsantos1
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
      - name: Commit e push
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "chore: atualiza snake.svg 🐍"
          add: "dist/*.svg"
